xvins_octomap_node:
  ros__parameters:
    octomap.resolution: 0.05
    octomap.prob_hit: 0.7
    octomap.prob_miss: 0.4
    octomap.occupancy_thresh: 0.5
    octomap.localmap_thresh: 3.0      # delete map if the occupied cells range is larger than this value
    octomap.pointcloudMaxX: 3.0
    octomap.pointcloudMinX: 0.0
    octomap.pointcloudMaxY: 3.0
    octomap.pointcloudMinY: -3.0
    octomap.pointcloudMaxZ: 4.0
    octomap.pointcloudMinZ: -2.0
    octomap.m_Expansion_range_x: 0.12  # Map expansion parameters in x
    octomap.m_Expansion_range_y: 0.12
    octomap.m_Expansion_range_z: 0.12
    octomap.m_isoccupiedThresh: 0.7    # Threshold for occupancy
    octomap.sub_cloud_from_xvins: true # true：Use cloud from XVINS false：Use cloud from depth image
    octomap.depth_pointcloudMaxX: 6.0  # Maximum X value for depth point cloud
    octomap.depth_pointcloudMinX: 0.1  # Minimum X value for depth point cloud
    octomap.depth_voxel_size: 0.08     # Voxel size for depth point cloud processing
    